SELECT [Id]
      ,[Name]
      ,[Subject]
      ,[HtmlContent]
      ,[TextContent]
      ,[Description]
      ,[IsActive]
      ,[CreatedAt]
      ,[CreatedBy]
      ,[LastModifiedAt]
      ,[LastModifiedBy]
  FROM [AuthSystemNewDb].[dbo].[EmailTemplates]
